### ISSUE TITLE
Aviso de malware

### ISSUE THREAD

**Issue by StivenKN** [DavidMojicaDev/FrontendAnimations#1]
![imagen](https://github.com/DavidMojicaDev/FrontendAnimations/assets/80909795/a9ab6dc2-3b13-45cf-8bb6-6ef4b41fc24c)

**Comment by DavidMojica** [comment]
> ![imagen](https://user-images.githubusercontent.com/80909795/272620426-a9ab6dc2-3b13-45cf-8bb6-6ef4b41fc24c.png)

![image](https://github.com/DavidMojicaDev/FrontendAnimations/assets/102682432/b16c678e-08aa-477d-84bd-604f51c97d50)

It's probable that your browser is flagging malware due to the absence of an SSL certificate detection. Try to change your browser before get in
